---
services:
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  serveur1:
    image: httpd:alpine
    depends_on:
      - php1
    networks:
      - frontend
      - backend
    volumes:
      - ./serveur1/html:/usr/local/apache2/htdocs
      - ./serveur1/conf:/usr/local/apache2/conf
  serveur2:
    image: httpd:alpine
    depends_on:
      - php2
    networks:
      - frontend
      - backend
    volumes:
      - ./serveur2/html:/usr/local/apache2/htdocs
      - ./serveur2/conf:/usr/local/apache2/conf
  php1:
    build: './php/'
    networks:
      - backend
    environment:
      - DB_USER=root
      - DB_PASSWD=rootpassword
    volumes:
      - ./serveur1/html:/usr/local/apache2/htdocs
  php2:
    build: './php/'
    networks:
      - backend
    environment:
      - DB_USER=root
      - DB_PASSWD=rootpassword
    volumes:
      - ./serveur2/html:/usr/local/apache2/htdocs
  mysql1:
    image: mysql:latest
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - dbdata1:/var/lib/mysql
  mysql2:
    image: mysql:latest
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - dbdata2:/var/lib/mysql

networks:
  frontend:
  backend:
volumes:
  dbdata1:
  dbdata2:
