upstream monsite-servers {
    server serveur1 max_fails=2;
    server serveur2 max_fails=2;
}
server {
    listen 80;
	listen  [::]:80;
    server_name tp3.com www.tp3.com;
	
	#access_log  /var/log/nginx/host.access.log  main;#access_log  /var/log/nginx/host.access.log  main;
	
	root   /usr/share/nginx/html;
    index  index.php index.html index.htm;

    location / {
		try_files $uri $uri/ /index.php?$query_string;
        proxy_pass         http://tp3-servers;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
    }
	
	#error_page  404              /404.html;
	
	# redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # PHP-FPM Configuration pour php
    location ~\.php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # deny access to .htaccess files
    #location ~ /\.ht {
    #    deny  all;
    #}
	
}
